config/routes.rb
Rails.application.routes.draw do


  resources :instruments do
    resources :locations
  end


  devise_for :users
  root to: 'pages#home'


  get 'instruments/:id/locations/:id', to: "locations#days"

  get 'dashboards/', to: "dashboards#dashboard_home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord

end

app/models/instrument.rb
class Instrument < ApplicationRecord

  belongs_to :user
  has_many :locations
  mount_uploader :photo, PhotoUploader


  BRANDS = ["Gibson", "Harman professionnal", "Shure", "Yamaha", "Fender", "Steinway", "Sennheiser", "Roland", "other brands"]
  CATEGORIES = ["chords", "wind", "drum", "other"].freeze

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  include PgSearch
  pg_search_scope :global_search,
    against: [ :title, :marque, :category, :description ],
    using: {
      tsearch: { prefix: true }
    }

end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :instruments
  has_many :locations

  # mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def dashboard_home
    @user = current_user
    authorize @user
    @locations = @user.locations
    @instruments = @user.instruments
    @instrument = Instrument.new
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_intrument, only: [:show, :edit, :update, :destroy]
  def index
    @location = Location.new
    @instruments = policy_scope(Instrument)
    @instruments = Instrument.where.not(latitude: nil, longitude: nil)
    if params[:type].present?
      @instruments = Instrument.global_search(params[:type])
    else
      @instruments = Instrument.all
    end

    if params[:where].present?

      @instruments = @instruments.near(params[:where], 10)

    end

    if params[:when].present? # && @instruments.present
      # raise
      @instruments = @instruments.where(present: true)

    end

    @markers = @instruments.map do |instrument|
      {
        lat: instrument.latitude,
        lng: instrument.longitude

        # infoWindow: { content: render_to_string(partial: "/instruments/map_box", locals: { flat: flat }) }
      }
    end
    authorize @instruments
  end

  def show
    @location = Location.new
    @rentings = Location.where(instrument_id: @instrument.id)
    @renting_dates = @rentings.map do |renting|
      {
        from: renting.start_date,
        to: renting.end_date
      }
    end
  end

  def new
    @instrument = Instrument.new
    authorize @instrument
    @instruments = Instrument.where.not(latitude: nil, longitude: nil)
    @user = current_user
    @markers = @instruments.map do |instrument|
      {
        lat: instrument.latitude,
        lng: instrument.longitude

        # infoWindow: { content: render_to_string(partial: "/instruments/map_box", locals: { flat: flat }) }
      }
    end

  end


  def create
    @instrument = Instrument.new(instruments_params)
    @instrument.user = current_user
    @instrument.address = current_user.address
    @instrument.save!
    if @instrument.save
      redirect_to instruments_path
    else
      flash.now[:error] = "Something is wrong! try again"
      render :new
    end
    authorize @instrument
  end

  def update

  end

  def edit

  end

  def destroy
    if @instrument.locations.empty?
      @instrument.destroy
      flash[:notice] = 'Instrument successfully destroyed'
    else
      flash[:alert] = 'This instrument has locations'
    end
    redirect_to dashboards_path
  end

  private

  def instruments_params
    params.require(:instrument).permit(:title, :description, :marque, :photo, :category, :address, :latitude, :longitude, :price )
  end

  def set_intrument
    @instrument = Instrument.find(params[:id])
    authorize @instrument
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
before_action :set_location, only: [:show, :days]
  def show
    days
  end

  def new
    @instrument = Instrument.find(params[:instrument_id])
    @location = Location.new
    authorize @location
  end

  def create
    @instrument = Instrument.find(params[:instrument_id])
    @location = Location.new(location_params)
    @location.user = current_user
    authorize @location
    @location.instrument = @instrument
    authorize @location
    if @location.save
      redirect_to instrument_location_path(@instrument, @location)
    else
      render :new
    end

  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    authorize @location
    redirect_to dashboards_path
  end

  def days
    @number = (@location.end_date - @location.start_date + 1).to_i
  end

  private
  def location_params
    params.require(:location).permit(:start_date, :end_date, :id, :instrument_id, :date)
  end

  def set_location
    @location = Location.find(params[:id])
    authorize @location
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/dashboard_home.html.erb
<div class="container-dashboard" >

  <div class="range">
    <div class="row">
        <!-- <p class="add"> My Instruments to rent <%#= link_to new_instrument_path do %> -->
          <!-- <i class="fas fa-plus" style="margin-left:30vw;"></i> -->
        <!-- <%# end %></p> -->
        <p class="add"> My Instruments to rent
          <i class="fas fa-plus" style="margin-left:30vw;" data-toggle="modal" data-target="#exampleModal"></i>
        </p>
      <% @instruments.each do |instrument|  %>
        <div class="card_dashboard" style="background-image: url('<%= cl_image_path instrument.photo if instrument.photo.present? %>');">
          <%= link_to instrument_path(instrument.id), method: :delete, :class => 'delete-link' do %>
           <i class='fas fa-trash-alt'></i>
          <% end %>
          <%= link_to edit_instrument_path(instrument.id), :class => 'edit-link' do %>
           <i class="fas fa-pencil-alt"></i>
          <% end %>
          <div class="card-description">
            <h2><%= instrument.title %></h2>
            <p><%= instrument.marque %></p>
          </div>
          <%= link_to '', instrument_path(instrument.id), class: "card-link" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="range">
    <div class="row">
      <p class="add"> My bookings </p>
      <% @locations.each do |location| %>
        <div class="card_dashboard " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= location.instrument.photo %>);">
            <div class="card-description">
              <h2><%= location.instrument.title %></h2>
              <p><%= location.instrument.marque %></p>
            </div>
            <h2 id="booked"> BOOKED </br> from <%= location.start_date %> to </br> <%= location.end_date %></h2>
              <%= link_to '', instrument_location_path(location.instrument, location), class: "card-link" %>
        </div>
      <%end %>
    </div>
  </div>


    <div class="range">
      <p class="add"> History </p>
    </div>

</div>

<%= render "instruments/instrument_form"  %>

app/views/dashboards/home.html.erb
<div class="container">

  <h1>Dashboard</h1>

  <div class="reservation"> Reservations </div>

  <div class="historique"> Historique</div>

  <div class="instrument_en_location"> Instrument en location</div>

</div>

app/views/instruments/_instrument_form.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <h3 class="title-update-create"> Add an instrument</h3>
              <%= simple_form_for @instrument do |f| %>


                <%= f.input :title, label: false, placeholder: 'Title' %>
                <%= f.input :marque, include_blank: false, collection: Instrument::BRANDS, label: false %>
                <%= f.input :price, label: false, placeholder: 'Price' %>

                <div class="button-icons">
                  <h4>Category:</h4>
                  <% Instrument::CATEGORIES.each do |category| %>
                    <div>
                      <%= image_tag "#{category}.png", height: 30, data: {name: category} %>
                    </div>
                  <% end %>
                </div>

                <%= f.input :category, as: :hidden, label: false %>
                <%= f.input :description %>
                <%= f.input :photo %>
                <%= f.input :photo_cache, as: :hidden %>
                <%= f.button :submit, class: "btn-medium"%>
              <% end %>
            </div>

          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/instruments/destroy.html.erb
<h1>Instrument#destroy</h1>

app/views/instruments/edit.html.erb
<h2 class="title-update-create"> Update my instrument</h1>

<%= render "instrument_form" %>

app/views/instruments/index.html.erb
<!-- <h1>Instruments#index</h1>
<p>Find me in app/views/instruments/index.html.erb</p>
 -->
<div id="banner" class="banner-instrument" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.7) 50%), url('<%= image_path "duotone.png" %>')">

      <div class="form-wrapper cf">
      <!-- <div class="form-inline " > -->
        <%= form_tag instruments_path, method: :get, :class => "form-inline" do %>
        <%= text_field_tag :type,
           params[:type],
           class:"form-control input",
           # id: "flat_address",
            placeholder: "find your instrument"
        %>

        <%= text_field_tag :where,
           params[:where],
           class:"form-control input where",
           id: "flat_address",
            placeholder: "Where ?"
        %>

        <%= text_field_tag :when,
           params[:when],
           class:"form-control input when datepicker-home",
           # id: "flat_address",
            placeholder: "When ?"
        %>
          <%= button_tag class: "button" do %>
            <%= icon('fa', 'search') %>
          <% end %>
        <% end %>
      </div>
              <!-- <input type="text" placeholder="Search here..." required>
              <button type="submit">Search</button> -->
      <!-- </div> -->
  <div class="banner-content">

  </div>
</div>


<div class="container-back">
  <div class="container">
    <div class="row">
        <% @instruments.each do |instrument|  %>
      <div class="col-xs-6">

          <div class="card" style="background-image:url('<%= cl_image_path instrument.photo if instrument.photo.present? %>');" data-toggle="modal" data-target="#Modal-<%= instrument.id %>">
              <%#= link_to '', instrument_path(instrument), class: "card-link " %>
            <div class="card-description">

              <h2><%= instrument.title %></h2>

              <p><%= instrument.marque %></p>
              <p><%= instrument.price %>€/jour</p>
            </div>
          </div>
          <%= render 'locations/form', location: @location, instrument: instrument, id: instrument.id, class:"date-picker" %>
      </div>
        <% end %>
    </div>
  </div>
        <!-- insert <div class="card"> -->
  <div class="container-map">
    <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>">
    </div>
  </div>
</div>

app/views/instruments/new.html.erb
<%= render "instrument_form" %>

app/views/instruments/show.html.erb
<div class="container " >
      <%= render 'locations/form', location: @location, class:"date-picker" %>
</div>

app/views/instruments/update.html.erb
<h1>Instruments#update</h1>
<p>Find me in app/views/instruments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ziknb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- NEW! -->
<!--     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous"> -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600,700" rel="stylesheet">
    <!-- <%#= stylesheet_pack_tag 'application', media: 'all' %> Uncomment if you import CSS in app/javascript/packs/application.js -->




    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
      <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/locations/_form.html.erb
<div class="modal fade" id="Modal-<%= id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div style="background-color: white;">

      <div class="modal-body">
      <%= simple_form_for([instrument, @location]) do |l| %>
        <div class='col-sm-14 ' style="background-color: white;" align="center">
          <div class="form-inline" data-inline="true">
            <%= l.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            <%= l.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            <div class="action">
            <%= l.submit  "book ", class: "btn-medium " %>
          </div>
          </div>
        </div>
      </div>

        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/locations/destroy.html.erb
<h1>LocationsController#destroy</h1>
<p>Find me in app/views/locations_controller/destroy.html.erb</p>

app/views/locations/show.html.erb
<div class="container-instru" style="background-image: linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0.5)), url('<%= image_path "duotone2.png" %>');">


    <div class="loc">
      <div class="card" style="background-image: url('<%= cl_image_path @location.instrument.photo if @location.instrument.photo.present? %>'); background-size:cover;">
      </div>



      <div class="box">
          <h2> Details of your booking</h2>
            <p><strong>FROM:  </strong> <%= @location.start_date %></p>
            <p><strong>TO:  </strong><%= @location.end_date %></p>
            <div class="days">
              <p>(Number of days of the booking: <strong><%= pluralize @number, "day" %></strong>) </p>
            </div>
            <p><strong>Rented instrument:  </strong><%= @location.instrument.title %></p>
      </div>
      <div class="but">
        <div class = "button" style="margin-left: 30px;">
           <%= link_to("Back to dashboard", dashboards_path, class: "btn-medium") %>
        </div>
        <div class="bin">
          <div class = "button" style="margin-left: 30px;">
            <%= link_to("Cancel the booking", instrument_location_path(@location.instrument, @location), method: :delete, class: "btn-medium") %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.2) 0%, rgba(0,36,61,0.5) 50%), url('<%= image_path "duotone.png" %>')">
  <div class="banner-content">
    <h1>Zick'n'b</h1>
  <svg> <path style="stroke: #ffffff; stroke-width:10px; stroke-linecap: round; fill:none;" d="M10, 10, L50, 100, L90, 50"></path>
  </svg>

    <p id="catch_phrase">Rent instruments & share musical experiences</p>
  </div>
  <% if user_signed_in? %>
    <%= link_to "Start !", instruments_path, class: 'btn-medium color'  %>
<% else  %>
<%= link_to "Start !", new_user_registration_path, class: 'btn-medium color' %>
  <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to instruments_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Dashboard", dashboards_path, class: "navbar-wagon-item navbar-wagon-link btn-medium" %>
      <%= link_to "Instruments", instruments_path, class: "navbar-wagon-item navbar-wagon-link btn-medium" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/adrienblue", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>